static BOOLEAN all_digits (STRING);
static BOOLEAN buffer_to_line (STRING, INT *, STRING *, STRING *, STRING *, STRING *);
static BOOLEAN translate_values (NODE);
static CACHE create_cache (INT, INT);
static CACHEEL add_to_direct (CACHE, STRING);
static CACHEEL key_to_cacheel (CACHE, STRING, STRING);
static ENTRY fndentry (TABLE, STRING);
static INT (int);
static INT add_even_defn (STRING, INT);
static INT add_fam_defn (STRING, INT);
static INT add_indi_defn (STRING, INT, ELMNT *);
static INT add_othr_defn (STRING, INT);
static INT add_sour_defn (STRING, INT);
static INT add_to_structures(STRING, ELMNT);
static INT codeof (int);
static INT get_date_tok (INT *, STRING *);
static INT hash (STRING);
static INT index (STRING, STRING, INT);
static LNODE nth_in_list (LIST, INT);
static NODE even_to_even (NODE);
static NODE fam_to_fam (NODE);
static NODE indi_to_indi (NODE);
static NODE key_to_node (CACHE, STRING, STRING);
static NODE othr_to_othr (NODE);
static NODE sour_to_sour (NODE);
static RKEY refn2rkey (STRING);
static STRING format_day (INT, INT);
static STRING format_month (INT, INT);
static STRING format_year (INT, INT);
static STRING nextpiece (STRING);
static STRING parts_to_name (STRING *);
static check_even_links (ELMNT);
static check_fam_links (ELMNT);
static check_indi_links (ELMNT);
static check_othr_links (ELMNT);
static check_references (void);
static check_sour_links (ELMNT);
static clear_structures (void);
static compute_pi (STRING);
static del_in_dbase (STRING);
static dereference (CACHEEL);
static direct_to_first (CACHE, CACHEEL);
static direct_to_indirect (CACHE);
static first_direct (CACHE, CACHEEL);
static first_indirect (CACHE, CACHEEL);
static handle_fam_lev1 (STRING, STRING, INT);
static handle_indi_lev1 (STRING, STRING, INT);
static handle_value (STRING, INT);
static indirect_to_first (CACHE, CACHEEL);
static init_monthtbl (void);
static name_to_parts (STRING, STRING *);
static remove_direct (CACHE, CACHEEL);
static remove_indirect (CACHE, CACHEEL);
static remove_last (CACHE);
static restore_record (int, int, INT);
static set_date_string (STRING);
static squeeze (STRING, STRING);
