.TH dbverify 1 "2007 Oct" "Lifelines 3.0.62"
.SH NAME
dbverify \- Check a Lifelines database
.SH SYNOPSIS
.B dbverify
[
.I options
] 
.I file
.br
.SH DESCRIPTION
This manual page documents briefly the
.B dbverify
command.
.PP
The dbverify program is a companion program of the 
.I Lifelines
genealogy software, and is used to check an existing lifelines
database for errors.
.PP
.SH OPTIONS
.PP
.TP
.BI \-a
Perform all checks (does not include fixes)
.TP
.BI \-g
Check for ghosts (names/refns)
.TP
.BI \-G
Check for & fix ghosts (names/refns)
.TP
.BI \-i
Check individuals
.TP
.BI \-f
Check families
.TP
.BI \-F
Alter any bad family lineage pointers (to _badptr)
.TP
.BI \-h
command-line help
.TP
.BI \-s
Check sours
.TP
.BI \-e
Check events
.TP
.BI \-x
Check others
.TP
.BI \-l
Check database structure
.TP
.BI \-m
Check for records missing data entries
.TP
.BI \-M
Fix records missing data entries
.TP
.BI \-D
Fix bad delete entries
.TP
.BI \-n
Noisy (echo every record processed)
.SH AUTHOR
This manual page was written by Christian Perrier <bubulle@debian.org>,
for the Debian GNU/Linux system (but may be used by others).

