.TH lldump 1 "2019 Sep" "Lifelines 3.2.0"
.SH NAME
lldump \- Dump a Lifelines database
.SH SYNOPSIS
.B lldump
[
.I options
] 
.I file
.br
.SH DESCRIPTION
This manual page documents briefly the
.B lldump
command.
.PP
The lldump program is a companion program of the 
.I Lifelines
genealogy software, and is used to dump various records of 
an existing lifelines database, mainly for debugging purposes.
.PP
.SH OPTIONS
.PP
.TP
.BI \-a
Dump ALL records
.TP
.BI \-b
Dump btree (INDEX) records
.TP
.BI \-k
Dump key records (KEYFILE1, KEYFILE2)
.TP
.BI \-x
Dump xref records (DELETESET)
.TP
.BI \-r
Dump block records (BLOCK)
.TP
.SH AUTHOR
This manual page was written by Matt Emmerton <matt@gsicomp.on.ca>.

